# Generated by Django 4.2.3 on 2023-10-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insumo', '0002_remove_insumo_grupo_insumo_certificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmedida',
            name='unidad',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
