# Generated by Django 4.2.3 on 2023-10-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insumo', '0003_unidadmedida_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadmedida',
            name='nombre',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
