# Generated by Django 4.2.3 on 2023-11-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insumo', '0004_alter_unidadmedida_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='insumos',
            field=models.ManyToManyField(blank=True, null=True, related_name='grupos', to='Insumo.insumo'),
        ),
    ]
