# Generated by Django 4.2.3 on 2023-11-29 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Insumo', '0005_alter_grupo_insumos'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='carencia',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='insumo',
            name='ingrediente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Insumo.ingredienteactivo'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='nombre',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
