# Generated by Django 4.2.3 on 2023-11-30 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insumo', '0007_alter_insumo_codigo_contable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificacion',
            name='ingrediente_activo',
        ),
        migrations.RemoveField(
            model_name='certificacion',
            name='periodo_carencia',
        ),
    ]
