# Generated by Django 4.2.3 on 2023-07-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit_cedula', models.CharField(max_length=20)),
                ('razon_social', models.CharField(max_length=100, null=True)),
                ('representante_legal', models.CharField(max_length=100, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vereda', models.CharField(max_length=100, null=True)),
                ('departamento', models.CharField(max_length=100, null=True)),
                ('municipio', models.CharField(max_length=100, null=True)),
                ('barrio', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
