# Generated by Django 4.2.3 on 2023-11-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0002_alter_proveedor_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='tipo_documento',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
