# Generated by Django 4.2.3 on 2023-07-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.CharField(max_length=10)),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('de_finca', models.CharField(max_length=100, null=True)),
                ('a_finca', models.CharField(max_length=100, null=True)),
                ('insumo', models.CharField(max_length=100, null=True)),
                ('grupo', models.CharField(max_length=100, null=True)),
                ('medida', models.CharField(max_length=50, null=True)),
                ('existencia', models.FloatField()),
                ('cantidad', models.FloatField()),
                ('valor_unitario_salida', models.FloatField()),
                ('valor_unitario_entrada_a', models.FloatField()),
                ('total_entra_a_la_finca', models.FloatField()),
            ],
        ),
    ]
