# Generated by Django 4.2.3 on 2023-08-01 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entrada', '0003_alter_entrada_insumo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='existencia',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='medida',
        ),
    ]
