# Generated by Django 4.2.3 on 2023-08-01 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entrada', '0004_remove_entrada_existencia_remove_entrada_grupo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='semana',
        ),
    ]
