# Generated by Django 4.2.3 on 2023-08-01 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entrada', '0005_remove_entrada_semana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='valor_unitario_salida',
        ),
    ]
