# Generated by Django 4.2.3 on 2023-08-01 21:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Entrada', '0007_remove_entrada_id_entrada_identificador'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
