# Generated by Django 4.2.3 on 2023-08-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrada', '0008_entrada_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
