# Generated by Django 4.2.3 on 2023-08-01 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Insumo', '0002_remove_insumo_grupo_insumo_certificacion_and_more'),
        ('Fincas', '0002_remove_finca_email_remove_finca_propietario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Entrada', '0009_alter_entrada_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEntrada',
            fields=[
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False)),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('cantidad', models.FloatField()),
                ('valor_unitario_entrada_a', models.FloatField()),
                ('total_entra_a_la_finca', models.FloatField()),
                ('identificador', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('a_finca', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Fincas.finca')),
                ('de_finca', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Fincas.finca')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('insumo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Insumo.insumo')),
            ],
            options={
                'verbose_name': 'historical entrada',
                'verbose_name_plural': 'historical entradas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
