# Generated by Django 4.2.3 on 2023-08-22 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entrada', '0010_historicalentrada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='desde',
            new_name='fecha_ingreso',
        ),
        migrations.RenameField(
            model_name='historicalentrada',
            old_name='desde',
            new_name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='hasta',
        ),
        migrations.RemoveField(
            model_name='historicalentrada',
            name='hasta',
        ),
    ]
