# Generated by Django 4.2.3 on 2023-08-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrada', '0011_rename_desde_entrada_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='fecha_ingreso',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalentrada',
            name='fecha_ingreso',
            field=models.DateTimeField(),
        ),
    ]
