# Generated by Django 4.2.3 on 2023-08-29 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrada', '0018_alter_entrada_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='identificador',
        ),
        migrations.RemoveField(
            model_name='historicalentrada',
            name='identificador',
        ),
        migrations.AddField(
            model_name='entrada',
            name='id',
            field=models.IntegerField( primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='historicalentrada',
            name='id',
            field=models.IntegerField(db_index=True ),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 29, 18, 14, 4, 845272)),
        ),
        migrations.AlterField(
            model_name='historicalentrada',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 29, 18, 14, 4, 845272)),
        ),
    ]
