# Generated by Django 4.2.3 on 2023-08-30 01:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0001_initial'),
        ('Insumo', '0002_remove_insumo_grupo_insumo_certificacion_and_more'),
        ('Entrada', '0021_alter_entrada_fecha_ingreso_alter_entrada_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='de_finca',
            new_name='finca',
        ),
        migrations.RenameField(
            model_name='historicalentrada',
            old_name='a_finca',
            new_name='finca',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='a_finca',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='total_entra_a_la_finca',
        ),
        migrations.RemoveField(
            model_name='historicalentrada',
            name='de_finca',
        ),
        migrations.RemoveField(
            model_name='historicalentrada',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='historicalentrada',
            name='total_entra_a_la_finca',
        ),
        migrations.AddField(
            model_name='entrada',
            name='factura',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='fecha_vencimiento',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 29, 20, 27, 9, 7281)),
        ),
        migrations.AddField(
            model_name='entrada',
            name='numero_factura',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='entrada',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Proveedor.proveedor'),
        ),
        migrations.AddField(
            model_name='historicalentrada',
            name='factura',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalentrada',
            name='fecha_vencimiento',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 29, 20, 27, 9, 7281)),
        ),
        migrations.AddField(
            model_name='historicalentrada',
            name='numero_factura',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historicalentrada',
            name='proveedor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Proveedor.proveedor'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='insumo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Insumo.insumo'),
        ),
    ]
