# Generated by Django 4.2.3 on 2023-08-30 01:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fincas', '0005_remove_finca_bodegas_lotes_bodegas'),
        ('Entrada', '0022_rename_de_finca_entrada_finca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='finca',
        ),
        migrations.RemoveField(
            model_name='historicalentrada',
            name='finca',
        ),
        migrations.AddField(
            model_name='entrada',
            name='bodega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas_de_finca', to='Fincas.bodegas'),
        ),
        migrations.AddField(
            model_name='historicalentrada',
            name='bodega',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Fincas.bodegas'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='fecha_vencimiento',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 29, 20, 34, 55, 76900)),
        ),
        migrations.AlterField(
            model_name='historicalentrada',
            name='fecha_vencimiento',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 29, 20, 34, 55, 76900)),
        ),
    ]
