# Generated by Django 4.2.3 on 2023-08-30 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrada', '0023_remove_entrada_finca_remove_historicalentrada_finca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='fecha_vencimiento',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 14, 57, 36, 175742)),
        ),
        migrations.AlterField(
            model_name='historicalentrada',
            name='fecha_vencimiento',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 14, 57, 36, 175742)),
        ),
    ]
