# Generated by Django 4.2.3 on 2023-08-30 20:13

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Entrada', '0024_alter_entrada_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='id',
        ),
        migrations.RemoveField(
            model_name='historicalentrada',
            name='id',
        ),
        migrations.AddField(
            model_name='entrada',
            name='identificador',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='historicalentrada',
            name='identificador',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='fecha_vencimiento',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 15, 13, 24, 992826)),
        ),
        migrations.AlterField(
            model_name='historicalentrada',
            name='fecha_vencimiento',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 15, 13, 24, 992826)),
        ),
    ]
