# Generated by Django 4.2.3 on 2023-09-07 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrada', '0025_remove_entrada_id_remove_historicalentrada_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='fecha_vencimiento',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 7, 27, 36, 834418)),
        ),
        migrations.AlterField(
            model_name='historicalentrada',
            name='fecha_vencimiento',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 7, 27, 36, 834418)),
        ),
    ]
