# Generated by Django 4.2.3 on 2023-11-02 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrada', '0041_alter_entrada_factura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='fecha_vencimiento',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 2, 17, 47, 55, 382710)),
        ),
        migrations.AlterField(
            model_name='historicalentrada',
            name='fecha_vencimiento',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 2, 17, 47, 55, 382710)),
        ),
    ]
