# Generated by Django 4.2.3 on 2023-07-19 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Fincas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finca',
            name='email',
        ),
        migrations.RemoveField(
            model_name='finca',
            name='propietario',
        ),
        migrations.AddField(
            model_name='finca',
            name='telefono',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='finca',
            name='ubicacion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='finca',
            name='nombre_finca',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='finca',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
