# Generated by Django 4.2.3 on 2023-08-24 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Fincas', '0002_remove_finca_email_remove_finca_propietario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finca',
            name='usuario',
        ),
        migrations.CreateModel(
            name='Lotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lote', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(default='', max_length=150, null=True)),
                ('hectareas', models.FloatField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bodegas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_bodega', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(default='', max_length=150, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='finca',
            name='bodegas',
            field=models.ManyToManyField(null=True, related_name='bodegas_finca', to='Fincas.bodegas'),
        ),
        migrations.AddField(
            model_name='finca',
            name='lotes',
            field=models.ManyToManyField(null=True, related_name='lotes_finca', to='Fincas.lotes'),
        ),
        migrations.AddField(
            model_name='finca',
            name='usuario',
            field=models.ManyToManyField(null=True, related_name='usuarios_finca', to=settings.AUTH_USER_MODEL),
        ),
    ]
