# Generated by Django 4.2.3 on 2023-08-24 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Fincas', '0003_remove_finca_usuario_lotes_bodegas_finca_bodegas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodegas',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='lotes',
            name='usuario',
        ),
        migrations.AddField(
            model_name='bodegas',
            name='usuario',
            field=models.ManyToManyField(null=True, related_name='bodegas_finca_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lotes',
            name='usuario',
            field=models.ManyToManyField(null=True, related_name='lotes_finca_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
