# Generated by Django 4.2.3 on 2023-08-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fincas', '0004_remove_bodegas_usuario_remove_lotes_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finca',
            name='bodegas',
        ),
        migrations.AddField(
            model_name='lotes',
            name='bodegas',
            field=models.ManyToManyField(null=True, related_name='bodegas_finca', to='Fincas.bodegas'),
        ),
    ]
