# Generated by Django 4.2.3 on 2023-09-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fincas', '0005_remove_finca_bodegas_lotes_bodegas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finca',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='lotes',
            name='usuario',
        ),
    ]
