# Generated by Django 4.2.3 on 2023-10-02 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fincas', '0007_infouser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finca',
            name='lotes',
        ),
        migrations.RemoveField(
            model_name='lotes',
            name='bodegas',
        ),
        migrations.AddField(
            model_name='bodegas',
            name='lote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bodegas', to='Fincas.lotes'),
        ),
        migrations.AddField(
            model_name='lotes',
            name='finca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='Fincas.finca'),
        ),
    ]
