# Generated by Django 4.2.3 on 2024-02-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fincas', '0008_remove_finca_lotes_remove_lotes_bodegas_bodegas_lote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodegas',
            name='codigo',
            field=models.CharField(default='', max_length=5, null=True),
        ),
    ]
