# Generated by Django 4.2.3 on 2024-02-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fincas', '0009_bodegas_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='finca',
            name='codigo',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
