# Generated by Django 4.2.3 on 2023-08-01 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salida', '0002_remove_salida_existencia_remove_salida_grupo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salida',
            name='valor_unitario_entrada_a',
        ),
    ]
