# Generated by Django 4.2.3 on 2023-08-01 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salida', '0003_remove_salida_valor_unitario_entrada_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salida',
            name='desde',
        ),
        migrations.RemoveField(
            model_name='salida',
            name='hasta',
        ),
    ]
