# Generated by Django 4.2.3 on 2023-08-01 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fincas', '0002_remove_finca_email_remove_finca_propietario_and_more'),
        ('Salida', '0004_remove_salida_desde_remove_salida_hasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='a_finca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salidas_a_finca', to='Fincas.finca'),
        ),
        migrations.AlterField(
            model_name='salida',
            name='de_finca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salidas_de_finca', to='Fincas.finca'),
        ),
    ]
