# Generated by Django 4.2.3 on 2023-08-22 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salida', '0005_alter_salida_a_finca_alter_salida_de_finca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salida',
            name='semana',
        ),
        migrations.AddField(
            model_name='salida',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 17, 59, 12, 271691)),
        ),
    ]
