# Generated by Django 4.2.3 on 2023-08-30 19:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fincas', '0005_remove_finca_bodegas_lotes_bodegas'),
        ('Insumo', '0002_remove_insumo_grupo_insumo_certificacion_and_more'),
        ('Salida', '0017_alter_salida_fecha_ingreso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salida',
            old_name='total_entra_a_la_finca',
            new_name='valor_unitario_entrada',
        ),
        migrations.RemoveField(
            model_name='salida',
            name='a_finca',
        ),
        migrations.RemoveField(
            model_name='salida',
            name='de_finca',
        ),
        migrations.AddField(
            model_name='salida',
            name='a_bodega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrada_a_bodega', to='Fincas.finca'),
        ),
        migrations.AddField(
            model_name='salida',
            name='de_bodega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salidas_de_bodega', to='Fincas.finca'),
        ),
        migrations.AddField(
            model_name='salida',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupo_insumo_salida', to='Insumo.grupo'),
        ),
        migrations.AlterField(
            model_name='salida',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 14, 57, 36, 206287)),
        ),
    ]
