# Generated by Django 4.2.3 on 2023-08-30 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salida', '0018_rename_total_entra_a_la_finca_salida_valor_unitario_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 15, 13, 25, 6823)),
        ),
    ]
