# Generated by Django 4.2.3 on 2023-10-11 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salida', '0024_alter_salida_fecha_ingreso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salida',
            old_name='valor_unitario_entrada',
            new_name='valor_total_salida',
        ),
        migrations.RemoveField(
            model_name='salida',
            name='a_bodega',
        ),
        migrations.RemoveField(
            model_name='salida',
            name='de_bodega',
        ),
        migrations.RemoveField(
            model_name='salida',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='salida',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='salida',
            name='valor_unitario_salida',
        ),
        migrations.AddField(
            model_name='salida',
            name='fecha_salida',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 11, 10, 6, 28, 202472)),
        ),
    ]
