# Generated by Django 4.2.3 on 2023-10-11 15:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entrada', '0032_alter_entrada_fecha_vencimiento_and_more'),
        ('Salida', '0025_rename_valor_unitario_entrada_salida_valor_total_salida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='fecha_salida',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 11, 10, 15, 34, 694469)),
        ),
        migrations.CreateModel(
            name='SalidaEntradaRelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.FloatField()),
                ('precio_unitario', models.FloatField()),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrada.entrada')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salida.salida')),
            ],
        ),
    ]
