# Generated by Django 4.2.3 on 2023-10-24 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salida', '0026_alter_salida_fecha_salida_salidaentradarelacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='fecha_salida',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 17, 49, 6, 713487)),
        ),
    ]
