# Generated by Django 4.2.3 on 2023-10-25 16:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entrada', '0034_alter_entrada_fecha_vencimiento_and_more'),
        ('Salida', '0027_alter_salida_fecha_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='fecha_salida',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 11, 32, 11, 120006)),
        ),
        migrations.AlterField(
            model_name='salidaentradarelacion',
            name='entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_entrada', to='Entrada.entrada'),
        ),
        migrations.AlterField(
            model_name='salidaentradarelacion',
            name='salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_salida', to='Salida.salida'),
        ),
    ]
