# Generated by Django 4.2.3 on 2023-10-26 02:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salida', '0028_alter_salida_fecha_salida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='fecha_salida',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 21, 17, 22, 154323)),
        ),
    ]
