# Generated by Django 4.2.3 on 2023-11-03 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salida', '0036_alter_salida_fecha_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='fecha_salida',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 12, 20, 28, 817877)),
        ),
    ]
