# Generated by Django 4.2.3 on 2023-11-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salida', '0041_alter_salida_fecha_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='movimientos',
            field=models.TextField(default='', null=True),
        ),
    ]
