# Generated by Django 4.2.3 on 2023-11-17 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salida', '0042_salida_movimientos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salidaentradarelacion',
            name='cantidad_usada',
        ),
        migrations.RemoveField(
            model_name='salidaentradarelacion',
            name='precio_unitario',
        ),
    ]
