# Generated by Django 4.2.3 on 2023-11-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrada', '0047_alter_entrada_fecha_vencimiento_and_more'),
        ('Salida', '0043_remove_salidaentradarelacion_cantidad_usada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salida',
            name='movimientos',
        ),
        migrations.AddField(
            model_name='salida',
            name='entradas',
            field=models.ManyToManyField(related_name='salidas_entradas', to='Entrada.entrada'),
        ),
        migrations.DeleteModel(
            name='SalidaEntradaRelacion',
        ),
    ]
