# Generated by Django 4.2.3 on 2023-11-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salida', '0044_remove_salida_movimientos_salida_entradas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='movimientos',
            field=models.TextField(default='', null=True),
        ),
    ]
